### PR TITLE
Enhance

### PR DESCRIPTION
**Pull request by seromenho**
This will allow devs to:
```js
Fliplet.Widget.get('com.fliplet.form').forms(UUID).mapData = function(data) {
  // Do whatever to data
  console.log(data);
  return data;
}
```

### CODE REVIEW

**Comment by squallstar** [comment]
I'd suggest an API like:

```js
Fliplet.Forms.getByUUID('uuid').beforeSend(function (data) {
  return processedData; // or a promise that resolves with the data
});
```

Don't forget widgets can register themselves via `Fliplet.Widget.register('name', fn)` like push notifications.

---

If you go for the register, you could do:

```js
Fliplet.Widget.register('com.fliplet.form', function () {
  return {
    get: function (uuid) {
      var form  // the form from a private variable above
      return {
        beforeSend: function (fn) {
          // push fn to a list of hooks to run before the form is sent
        }
      }
    }
 }
});
```

Usage:

```js
Fliplet.Widget.get('com.fliplet.form').get(123).beforeSend(function (rawData) {
  // return remapped data
});
```

**Comment by seromenho** [comment]
I see this more like a way to go for all widgets so devs can access them easily at the window scope.
So for:
1) I don't see much benefit from adding an API for each
2) Still thinking...

**Review by squallstar — CHANGES_REQUESTED** [review]
as per comments

**Comment by squallstar** [comment]
I made it simpler:

```js
var theForms = [];

// loop instances and put them on forms

Fliplet.Widget.register('com.fliplet.form', function () {
  return {
    forms: function () {
      return theForms;
    }
 }
});
```

**Review by squallstar — APPROVED** [review]

**Pull request merged**
